language: python
dist: xenial
python:
  - 3.6
  - 3.7
git:
  depth: 3
install:
  - pip3 install -r requirements.txt
script:
  - ./run-tests
notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
on_failure: always
